version: "3"

volumes:
  postgres_data:
    driver: local
  application_data:
    driver: local

services:
  postgres:
    image: postgres:14.4
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - 5432:5432
    restart: unless-stopped
  instagram:
    build: .
    container_name: python
    volumes:
      - application_data:/home/python/TeachMeSkills/Instagram
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    restart: unless-stopped
