"""First revision

Revision ID: 8148fcec5653
Revises: 
Create Date: 2022-10-03 22:57:28.262119

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "8148fcec5653"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "likes", ["id"])
    op.create_unique_constraint(None, "posts", ["id"])
    op.create_unique_constraint(None, "subscribers", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subscribers", type_="unique")
    op.drop_constraint(None, "posts", type_="unique")
    op.drop_constraint(None, "likes", type_="unique")
    # ### end Alembic commands ###
